version: '3.8'
services:
  user-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ms-email
    volumes:
      - postgres_sdata:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  postgres_sdata:
