server:
  port: 8081
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ms-email}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret}
  rabbitmq:
    addresses:


broker:
  queue:
    email:
      name: default.email
