server:
  port: 8081
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ms-email}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret}
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxxx@gmail.com
    password: xxxxx xxxx xxxx
    smtp:
      auth: true
      starttls:
        enable: true
  rabbitmq:
    addresses:

broker:
  queue:
    email:
      name: default.email
